name: lsp
on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install main deps
        run: yarn
      
      - name: Install main deps
        run: npm i -g tslib

      - name: Install package deps
        run: yarn bootstrap

      - name: Build packages
        run: yarn build

      - name: Lint packages
        run: yarn lint

      - name: Test packages
        run: yarn test

      - name: cdk diff
        if: ${{ env.AWS_ACCESS_KEY_ID != '' }}
        run: yarn cdk diff "*"
        working-directory: ./packages/cdk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: cdk deploy
        if: ${{ github.event_name == 'release' && env.AWS_ACCESS_KEY_ID != '' }}
        run: yarn cdk deploy --all --require-approval never
        working-directory: ./packages/cdk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
